@host = 127.0.0.1
@port = 5000
@baseUrl = http://{{host}}:{{port}}/api/users

@userId = 1

@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOjEsImlhdCI6MTczODE1NTUxNiwiZXhwIjoxNzM4MTU2NDE2fQ.FXP83a-fTrzVQ4w5_Ud1K8jijwW5XQ0qfCzd3gF0Iwk
@refresh = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOjEsImlhdCI6MTczODE1NTUxNiwiZXhwIjoxNzM4MTU2NDE2fQ.FXP83a-fTrzVQ4w5_Ud1K8jijwW5XQ0qfCzd3gF0Iwk

########## CRUD ##########
# Create new user
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "login": "admin",
  "password": "password",
  "role": "ADMIN"
}
###

# Update user
PATCH {{baseUrl}}/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "login": "Test"
}
###

# Delete user
DELETE {{baseUrl}}/{{userId}} HTTP/1.1
Content-Type: application/json
###

########## Listing ##########
# Get users list
GET {{baseUrl}}/ HTTP/1.1
{{authorization}}
###

# Find user by id
GET {{baseUrl}}/{{userId}} HTTP/1.1
Content-Type: application/json
###

########## Others ##########
# User login
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json
{{authorization}}

{
  "login": "admin",
  "password": "password"
}
###

# User login
POST {{baseUrl}}/token-refresh HTTP/1.1
Content-Type: application/json
{{refresh}}
###

# Roles guard test
GET {{baseUrl}}/test HTTP/1.1
{{authorization}}
###